README.md

I've got [some feedback](https://github.com/Happyr/TranslationBundle/pull/23#issuecomment-188829279) that documentation was missing about how to use this bundle without auto discovery. 
This PR adds a short explanation and example configuration.

Added example how to use the bundle without auto discovery

---

.travis.yml
composer.json

Test with --prefer-lowest

---

DependencyInjection/Compiler/DiscoveryPass.php
README.md

Updated links to the new documentation

---

CHANGELOG.md
Tests/autoload.php
phpunit.xml.dist

Fixes an issue introduced in composer 1.0:
https://github.com/puli/issues/issues/190

Fix Puli issue on PHP 5.6

---

.travis.yml

Symfony 3.1 has been released. Make sure we test for that as well

Test for Symfony3.1

---

ClientFactory/DummyClient.php

| Related tickets | related to #122 
See #122 for details.

DummyClient should provide methods of HttpClient and HttpAsyncClient

---

DependencyInjection/HttplugExtension.php
Resources/config/data-collector.xml

I did a code clean up and then removed a private service definition.

Minor fixes

---

DependencyInjection/HttplugExtension.php

| Related tickets | Fixes issues from scrutnizer
We do always have a ContainerBuilder.

We need the concrete implementation, not the interface.

---

CHANGELOG.md
composer.json

Changelog and `branch-alias` updates.

prepare 1.7 release

---

CHANGELOG.md

release 1.7.0

---

Resources/views/stack.html.twig
Resources/views/webprofiler.html.twig

| Related tickets | #196 
Fix remaining twig includes I forgot in #196.

Fix twig namespaces

---

composer.json

See https://github.com/php-http/HttplugBundle/blob/81efd33a63f7d4bcb1aec294415f1034fbb4349d/composer.json#L33.

Remove symfony/symfony dependency

---

.travis.yml

Removed extra test on php55

---

.travis.yml

Im currently developing a new tool. Could I start collecting some data from our builds?
It is no big secret but I've got nothing to show yet...

Share some data with a secret test tool by Nyholm

---

.travis.yml

Symfony 4 has been released, remove stability=rc

test with stable symfony 4 packages

---

composer.json

Improve branch alias

---

.travis.yml

also use php 7.3 for test runs with special environment settings.
follow up to #282

use php 7.3 for special tests

---

src/Resources/views/http_message.html.twig

Reference: https://github.com/php-http/HttplugBundle/pull/355#issuecomment-555062832

URLify header value links

---

src/Resources/config/data-collector.xml

| Related tickets | fixes #390

Add kernel.reset tag on DataCollector to be able to clear memory

---

.github/workflows/.editorconfig
.github/workflows/static-analysis.yml

editorconfig for the github actions

---

CHANGELOG.md
src/Resources/views/style/httplug.css.twig

Before:
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
After:
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
- Not compatible with Symfony < 4.2. Such Symfony versions are not maintained though. Worth adding conflict rule?

Fix dark mode design compatibility

---

CHANGELOG.md
src/Collector/ProfileClient.php
src/Collector/ProfilePlugin.php
src/Collector/Stack.php
src/Resources/views/stack.html.twig
src/Resources/views/style/httplug.css.twig

Changed tab texts inside profiler so that it shows ports in URL in case it's non-standard

---

.github/workflows/continuous-integration.yml
src/Collector/Formatter.php

| Related tickets | fixes #412
Implement the formatResponseForRequest method
To avoid the deprecation

implement formatResponseForRequest
