php-http/HttplugBundle

.editorconfig, .travis.yml, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, HttplugBundle.php, README.md, Resources/config/discovery.xml, Tests/Functional/ServiceInstantiationTest.php, Tests/Resources/Fixtures/config/empty.php, Tests/Resources/Fixtures/config/empty.xml, Tests/Resources/Fixtures/config/empty.yml, Tests/Resources/Fixtures/config/full.php, Tests/Resources/Fixtures/config/full.xml, Tests/Resources/Fixtures/config/full.yml, Tests/Resources/Fixtures/config/invalid.yml, Tests/Resources/app/AppKernel.php, Tests/Resources/app/config/config.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php, composer.json, phpunit.xml.dist
continued from #6
fix #7
once merged, we can move this repo to the php-http organisation.
=> building the initial bundle

.travis.yml, ClientFactory/ClientFactoryInterface.php, ClientFactory/DummyClient.php, ClientFactory/Guzzle5Factory.php, ClientFactory/Guzzle6Factory.php, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, Exception/InvalidConfiguration.php, HttplugBundle.php, README.md, Resources/config/discovery.xml, Resources/config/services.xml, Tests/Resources/Fixtures/config/full.php, Tests/Resources/Fixtures/config/full.xml, Tests/Resources/Fixtures/config/full.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php, composer.json
This will implement the feature mentioned in #10. 
This will let the user configure HttpClients for a specific implementation. Everything specific to a client, say guzzle5, is in one class. 
At the moment there is no validation of the special config. We just say: "The config you specify here is sent unparsed to Guzzle".
=> Make sure you can configure clients and register them as services

Collector/MessageJournal.php, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, README.md, Resources/config/data-collector.xml, Resources/config/plugins.xml, Resources/views/webprofiler.html.twig, Tests/Resources/Fixtures/config/empty.php, Tests/Resources/Fixtures/config/full.php, Tests/Resources/app/AppKernel.php, Tests/Unit/DependencyInjection/ConfigurationTest.php
As mentioned in #3. 
This PR implements a web debug toolbar. It uses the HistoryPlugin.
=> Added web profiler and toolbar

composer.json
=> fix dependencies

DependencyInjection/Configuration.php
If you configure the bundle with: 
```yaml
httplug:
clients:
guzzle:
factory: 'httplug.factory.guzzle6'
```
You would get an undefined array key error because we have no default value for the `config` node. This PR fix that issue.
=> Make sure we have a default config for the clients variable node

DependencyInjection/HttplugExtension.php
If you do not configure httplug at all it will use the auto discovery client. That client should also have the history plugin injected if you use the toolbar. 
Im not 100% confident in this PR. We will as always have two identifiers for the default client: `httplug.client` and `httplug.client.default`. This PR makes `httplug.client` a plugin client but not the other. 
Is this okey? The implications would be that you do not see the toolbar when using no configuration and the `httplug.client.default` service id.
=> Add history plugin to the auto discovery client

DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, HttplugBundle.php, README.md, Resources/config/plugins.xml, Tests/Unit/DependencyInjection/ConfigurationTest.php
This PR fixes #17 
```yaml
httplug: 
plugins: 
cache:
cache_pool: 'acme.cache'
config: 
respect_headers: true
logger:
formatter: 'acme.formatter'
```
This make sure that you can configure all our 9 configurable plugins. Some plugins (like `RetryPlugin`) has only optional configuration. They are enabled by default. They others are disabled by default. 
Also, the `LoggerPlugin` is treated special. We inject the `logger` service automatically and it is enabled by default. This is done because of ease of use.
=> Configure plugins

DependencyInjection/HttplugExtension.php
If we named a client to "default" we would get a circular reference because we are trying to add an alias named `httplug.client.default` for service `httplug.client.default`.
=> Bugfix, circular reference with client named 'default'

.travis.yml
Caching the entire Composer cache makes Travis to cache Packagist metadata too which are much more likely to make the cache stale too often (while downloaded package archives could still be cached).
=> only cache downloaded packages

.travis.yml, Tests/Resources/app/AppKernel.php, Tests/Resources/app/config/config_hhvm.yml, Tests/Resources/app/config/config_php.yml
This PR makes sure to include a different config file for the functional test when running HHVM. The new config file will not use auto discovery. 
This will fix #14
=> Make sure travis can run on HHVM

ClientFactory/CurlFactory.php, ClientFactory/ReactFactory.php, ClientFactory/SocketFactory.php, Resources/config/services.xml
Here are some minor (?) things I discovered when writing the docs...
=> Adding clients factories for Curl, React and Socket

Tests/Unit/ClientFactory/CurlFactoryTest.php, Tests/Unit/ClientFactory/Guzzle6FactoryTest.php, Tests/Unit/ClientFactory/ReactFactoryTest.php, Tests/Unit/ClientFactory/SocketFactoryTest.php, composer.json
This PR is a blocker for the tests to pass:  https://github.com/php-http/react-adapter/pull/10
=> Added tests for Guzzle6, Curl, React and Socket factories

HttplugFactory.php, Tests/Unit/HttplugFactoryTest.php
I did also rewrite the `evaluateCondition` function to support associative arrays. 
This will address one issue in #64
=> Added tests for Httplug factory

CHANGELOG.md, ClientFactory/BuzzFactory.php, Resources/config/services.xml, Tests/Unit/ClientFactory/BuzzFactoryTest.php, composer.json
I used the option resolver for this factory. That is because the Buzz Client constructor did not accept an array with config. The OptionsResolver lets me avoid lots of `isset($config['foo])`.
=> Added Buzz client factory

CHANGELOG.md, ClientFactory/PluginClientFactory.php, Collector/MessageJournal.php, DependencyInjection/HttplugExtension.php, Resources/config/data-collector.xml, Resources/config/plugins.xml, composer.json
| Deprecations?   | yes
Replaces php-http/plugins with php-http/common-client.
The plugins package has been deprecated and moved to client-common.
=> Replace plugins package with client-common

ClientFactory/CurlFactory.php
=> Allow CURL constant names

Resources/views/webprofiler.html.twig
| Documentation   | https://github.com/php-http/documentation/pull/118
While making screenshots for the documentation I noticed that the exception symbol was misplaced. Consider the screenshot below. 
When an exception is thrown at the error plugin we should have the big red X next to it. Before this PR the symbol appeared first at the content_length plugin.
=> Move the exception symbol one step up in the stack

CHANGELOG.md, DependencyInjection/HttplugExtension.php
Fixes the autodiscovery feature by using the appropriate discovery class.
https://github.com/php-http/HttplugBundle/blob/v1.2.0/DependencyInjection/HttplugExtension.php#L321
=> Fix autodiscovery

CHANGELOG.md, DependencyInjection/HttplugExtension.php
Fixes the bundle in production mode.
In production mode (and when debug mode is disabled) debug tools should not be registered in the clients, otherwise we get weird service not found errors.
=> Fix debug tool registration

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php
| BC breaks?      | yes
| Related tickets | fixes #70
Added support for BatchClient
=> Added batch client support

CHANGELOG.md, DependencyInjection/HttplugExtension.php
| BC breaks?      | yes
| Related tickets | fixes #92
With this PR we integrate with the WebProfiler timeline
=> Added stopwatch plugin

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php
| Related tickets | #112 (found bug while adding tests there - not adding test here to reduce conflicts)
Fix how we define the plugin services that have a `$config` parameter so they work.
They where broken.
=> fix plugin instantiation

Tests/Functional/ServiceInstantiationTest.php, Tests/Resources/app/AppKernel.php, Tests/Resources/app/config/config.yml, Tests/Resources/app/config/config_debug.yml
| New feature?    | no (only tests added)
| Related tickets | Test to prevent regression in #112
A test about the debug toolbar because tests in #112 where green but the toolbar broken.
We should prevent regressions.
=> test that journal is set up correctly

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, Resources/config/plugins.xml, Tests/Functional/ServiceInstantiationTest.php, Tests/Resources/Fixtures/config/full.php, Tests/Resources/Fixtures/config/full.xml, Tests/Resources/Fixtures/config/full.yml, Tests/Resources/Fixtures/config/invalid_plugin.yml, Tests/Resources/app/config/config.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Related tickets | fixes #110
| Documentation   | https://github.com/php-http/documentation/pull/142
Add new configuration for plugins specifically to a client. The global plugin configuration is duplicated to allow configuring all plugins with client specific information.
See #110
``` yaml
httplug:
plugins:
logger:
enabled: true
logger: 'logger'
formatter: null
redirect:
enabled: true
preserve_header: true
use_default_for_multiple: true
retry:
enabled: true
retry: 1
clients:
todo:
factory: "httplug.factory.guzzle6"
plugins:
- 'httplug.plugin.logger'
- 'httplug.plugin.redirect'
-  add_host:
host: http://localhost
- …
```
=> Allow to configure plugins specifically for a client

README.md
`php-http/client-implementation` makes sure we install a client otherwise composer installation fails.
=> Add information about client installation

Collector/DebugPluginCollector.php, Collector/RequestStackProvider.php, DependencyInjection/HttplugExtension.php, Resources/public/script/httplug.js, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| BC breaks?      | yes maybe
Fixed some typos
=> Fixed typos

.travis.yml
Stop testing the bundle against symfony/symfony 3.0 which is EOL and incompatible with twig/twig 2.x.
I also added symfony/symfony 3.2 in the matrix :)
Related symfony issue: https://github.com/symfony/symfony/issues/20284
=> Stop running tests for symfony 3.0 which is EOL

CHANGELOG.md, Resources/views/webprofiler.html.twig
| Related tickets | mentioned in #93 
This PR add profiler badges introduced with Symfony 2.8 profiler redesign.
- The toolbar icon is now displayed wit ha red background if there was errors.
- The toolbar hover add squared badges to display numbers.
- The failed request count badge is show using red background if a request failed.
- The profiler menu show the failed request count
=> show profiler badges in the toolbar and the menu

Collector/Collector.php, Collector/ProfilePlugin.php
| Related tickets | fixes #133
If we (for some reason) do not have a stack, it should not crash. Just pretend everything is normal. 
@dkvk, does this patch solve your issue?
=> Make sure we always have a stack

CHANGELOG.md, Collector/ProfileClient.php, Collector/ProfileClientFactory.php, Collector/Stack.php, Resources/config/data-collector.xml, Resources/views/webprofiler.html.twig, Tests/Unit/Collector/ProfileClientTest.php
| Related tickets | Partially #108, Partially #93, Partially #135 
This add tracking of request target url and method. I choose to decorate the Client at the lowest possible level (i.e not the PluginClient, but the inner one) to be able to catch what goes in and out the Client and avoid false informations because of the registered plugins.
Technically, when the profiling is enabled, each client factory is decorated with a `ProfileClientFactory` which returns the original client decorated with a `ProfileClient`.
This is what I suggested for #135 
Those new collected informations are required to write a …
=> add profile client

DependencyInjection/Configuration.php
| BC breaks?      | not really
All clients must be validated, not only the first one (which was the case due to returning during the first iteration of the loop over clients).
The easiest way to handle it is to put the validation inside the prototype node, so that each client is validated separately. This also allows to have a better error message (as the error message will tell you which client is invalid as the error will be inside the client configuration node).
The error message is also fixed to talk about the third incompatible features.
I answered `not really` for BC breaks, because there is a …
=> Fix the validation of incompatible options

Resources/config/services.xml
This configure the ``httplug.client`` as being the right choice for autowiring in Symfony 3.3+ when being asked to autowire a ``Http\Client\HttpClient`` typehint.
This also adds autowiring for all the message factory interfaces, using the main aliases as target.
Autowiring is one of the nice features of Symfony 3.3+ (working autowiring actually. We already have autowiring since 2.8 but it was not working well). So it is great to support it out of the box, especially when it has no impact for people using older versions or not using autowiring (the private alias just gets removed …
=> Enable autowiring support for symfony 3.3+

DependencyInjection/Configuration.php
The validation actually covers 3 incompatible messages, not 2 of them. My previous PR fixing the validation for clients added the name of the third option in the error message when I saw that it was missing, but I forgot to update the first sentence.
=> Fix the message about incompatible features

Tests/Unit/ClientFactory/BuzzFactoryTest.php, Tests/Unit/ClientFactory/CurlFactoryTest.php, Tests/Unit/ClientFactory/ReactFactoryTest.php, Tests/Unit/ClientFactory/SocketFactoryTest.php, Tests/Unit/Discovery/ConfiguredClientsStrategyTest.php
| Related tickets | N/A| Documentation   | N/A
I'm bored to see all those deprecated calls while running phpunit!
=> Replace deprecated calls to getMock in unit tests

DependencyInjection/HttplugExtension.php
| Related tickets | fixes #139 
This replace `clone` of plugin dependency injection definitions (which is bad as `Definition` does not support deep cloning) by `ChildDefinition` (or `DefinitionDecorator` in Symfony <3.3).
=> replace definition cloning with ChildDefinition

Discovery/ConfiguredClientsStrategy.php
Using late static binding to access private static properties is wrong, as child classes are not allowed to access them. This would lead to a fatal error when using a child class.
=> Fix access to private static properties

DependencyInjection/HttplugExtension.php, Resources/config/data-collector.xml, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Related tickets | N/A
Since #128, the `profiling.formatter` option is broken. So there is the fix with a unit test.
=> Fix broken profiling.formatter option

Collector/ProfileClientFactory.php, Tests/Unit/Collector/ProfileClientFactoryTest.php
| Related tickets | N/A
The ProfileClientFactory added in #136 was not tested and contained an error while decorating a callable factory. This is now fixed with tests.
=> Fix ProfileClient creation with callable factory

DependencyInjection/HttplugExtension.php
If both the client and the async client are null, the strategy would never find any candidates. In such case, it is useless to register it as a `kernel.request` listener to prepend itself to the discovery, as it would not have any effect on the discovery, but it requires work on each request.
=> Avoid registering the strategy listener when it is useless

DependencyInjection/HttplugExtension.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Related tickets | fixes #133 
Auto discovered clients were not visible in the profiler. This behavior is broken since at least 1.3. I didn't test any further back to find when it was broken.
This also fixes the root cause of #133. The easier way to test it is with `knplabs/github-api`.
The bug root cause was caused by the stopwatch plugin which was shared between every clients. When a client was configured, the stopwatch plugin gets decorated with the `ProfilePlugin` and when executed, no stack plugin was executed before.
So we have a plugin instance per client. I don't know if it's a good or a bad …
=> Display discovered clients in the profiler

CHANGELOG.md, Collector/Collector.php, Collector/ProfileClient.php, Collector/ProfileClientFactory.php, Collector/Stack.php, DependencyInjection/HttplugExtension.php, Resources/config/data-collector.xml, Resources/views/webprofiler.html.twig, Tests/Unit/Collector/ProfileClientFactoryTest.php, Tests/Unit/Collector/ProfileClientTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
**Depends on [stopwatch plugin PR](https://github.com/php-http/stopwatch-plugin/pull/3)**
Extended profiler toolbar item to display more details and duration
=> Extend profiler toolbar item

DependencyInjection/Configuration.php, Tests/Resources/Fixtures/config/full.php, Tests/Resources/Fixtures/config/full.xml, Tests/Resources/Fixtures/config/full.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php
| Related tickets | fixes #151
I would like to point out that the official documentation at http://docs.php-http.org/en/latest/plugins/cache.html does not mention the `hash_algo` configuration option.
=> expand configuration definition and adjust tests, closes #151

Resources/public/style/httplug.css, Resources/views/webprofiler.html.twig
| Related tickets | fixes #156 
This add the stack duration in the profiler.
=> Display stack duration in profiler

Resources/public/style/httplug.css
| Related tickets | N/A
Since #146, messages are truncated which may definitively hide informations to user. I replaced the `text-overflow: ellipsis` with a `overflow-x:auto` to display an horizontal scrollbar when required.
=> Display horizontal scrollbar when necessary for profiler messages

CHANGELOG.md, Collector/Formatter.php, Collector/ProfileClient.php, Collector/Stack.php, Resources/config/data-collector.xml, Resources/public/script/httplug.js, Resources/public/style/httplug.css, Resources/views/webprofiler.html.twig, Tests/Unit/Collector/FormatterTest.php, composer.json
| Related tickets | fixes #108 
This add the ability to copy any request from the profiler as cURL command!
I also reworked the profiler actions. I moved all possible actions to a kind of toolbar which contains copy as cURL, toggle profile stack and toggle body buttons.
=> Add copy as curl button in profiler

DependencyInjection/HttplugExtension.php
The stopwatch plugin is no longer required since time is now collected in ProfileClient.
This was forgotten in #135.
See https://github.com/php-http/HttplugBundle/pull/160#issuecomment-300380456
=> remove stopwatch plugin for discovered clients.

Collector/Collector.php, Collector/ProfileClient.php, Collector/ProfilePlugin.php
| BC breaks?      | yes, but they are not released yet
| Related tickets | fixes issues from scrutinizer
This is just a minor change in the return value of `getCurrentStack`
=> Make sure $stack is null or Stack. Never boolean.

DependencyInjection/HttplugExtension.php
=> Added docs and renamed configureSharedPlugins

DependencyInjection/Configuration.php, Tests/Resources/Fixtures/config/bc/issue-166.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php
This PR adds a test for an issue I found. 
We define `respect_cache_headers` like: 
```php
->enumNode('respect_cache_headers')
->info('Whether we should care about cache headers or not [DEPRECATED]')
->values([null, true, false])
->beforeNormalization()
->always(function ($v) {
@trigger_error('The option "respect_cache_headers" is deprecated since version 1.3 and will be removed in 2.0. Use "respect_response_cache_directives" instead.', E_USER_DEPRECATED);
return $v;
})
->end()
->end()
```
On Symfony 2.8, the EnumNode runs `array_unique` over the possible values. Though, `null` and `false` is treated the same. See https://3v4l.org/KWuNP
This will result in that the possible values for `respect_cache_headers` will only be `true` and `null`. This issue will break BC since we promise that …
=> Allow respect_cache_headers to be "false"

Collector/Profile.php, Collector/ProfilePlugin.php, Tests/Unit/Collector/ProfilePluginTest.php
As I explained on Slack, before this fix, the request was collected before the decorated plugin execution and so, changes to the request made by the plugin were displayed in the next plugin in the chain.
Now the request is collected after the plugin execution and so, the plugin changes are displayed within the right plugin block.
Before:
After:
=> Collect the request after the plugin execution

ClientFactory/AutoDiscoveryFactory.php, DependencyInjection/Configuration.php, Resources/config/data-collector.xml, Resources/config/services.xml
=> Allow you to skip the factory keyword.

README.md
clarify the installation instructions in the README.
fix #172
=> clarify installation

.travis.yml, Tests/Unit/Collector/FormatterTest.php
Same as https://github.com/php-http/message/pull/77.
=> build hhvm on trusty box

Tests/Unit/Collector/FormatterTest.php, Tests/Unit/Collector/ProfileClientTest.php, Tests/Unit/Collector/ProfilePluginTest.php, Tests/Unit/Collector/StackPluginTest.php
| Related tickets | partially #175 
This is a cleanup of tests to stop mocking immutable/value objects.
`Psr\Http\Message\MessageInterface` and `Psr\Http\Message\ResponseInterface`
mocks are replaced with `GuzzleHttp\Psr7\Request` and
`GuzzleHttp\Psr7\Response` respectively.
`Http\Promise\Promise` mocks are replaced either with
`Http\Client\Promise\HttpFulfilledPromise` or
`Http\Client\Promise\HttpRejectedPromise` depending on the test
requirements.
This make tests easier to read, thus  to maintain, etc... Also this will help me to solve #175 as it will require some profiling rewrite.
=> Stop mocking immutable/value objects

Collector/ProfilePlugin.php, Tests/Functional/ProfilingTest.php, Tests/Unit/Collector/ProfilePluginTest.php, composer.json
| Bug fix?        | not yet
| Related tickets | N/A
This a a failing functional test about profiling when the `CachePlugin` is involved.
When the cache is hit and the `CachePlugin` does not perform any cache validation, the `ProfileClient` is never reached. This cause the profiled stack about not being complete and will display empty boxes in the profiler panel.
=> Profiling might not work with CachePlugin

CHANGELOG.md, Collector/ProfilePlugin.php, DependencyInjection/HttplugExtension.php, Tests/Unit/Collector/ProfilePluginTest.php
| Related tickets | partially #109
| Documentation   | screenshot updates
This use the plugin FQCN instead of the service name in the profiler (see https://github.com/php-http/HttplugBundle/issues/109#issuecomment-308970141).
=> display plugin fqcn instead of plugin service id

Collector/Collector.php, DependencyInjection/HttplugExtension.php, Tests/Unit/Collector/CollectorTest.php
This is a subset of #109 which aims to display clients names in the profiler from what is collected. The only "negative" change here is we no longer display empty tabs for clients which doesn't sent any request.
=> guess client names from collected stacks

Tests/Functional/DiscoveredClientsTest.php, Tests/Resources/app/config/config.yml, composer.json
This just add functional tests on discovered clients as I will refactor this to use xml configuration instead of PHP in `HttplugExtension`. This will help me to not break discovered clients!
=> Add discovered clients functional tests

Collector/Collector.php, Collector/ProfileClient.php, Collector/ProfilePlugin.php, Collector/Stack.php, Collector/StackPlugin.php, Resources/public/style/httplug.css, Resources/views/stack.html.twig, Resources/views/webprofiler.html.twig, Tests/Unit/Collector/CollectorTest.php, Tests/Unit/Collector/ProfileClientTest.php, Tests/Unit/Collector/ProfilePluginTest.php, Tests/Unit/Collector/StackPluginTest.php, composer.json
| Documentation   | update screenshots?
While working on #109, I just discovered the refactoring I was doing allows to easily display children requests as nested in the profiler. To keep things small, I decided to do a separate PR which add a nice feature in the profiler and helps to fix #109.
This introduce the concept of active stack. When coming into the StackPlugin, the created stack is made active. Then the request go through every plugins to reach the ProfileClient. The ProfileClient deactivate the stack. Then other code execute, maybe an other request. Then when ProfileClient callbacks …
=> display children requests as nested in the profiler

DependencyInjection/HttplugExtension.php, Resources/config/data-collector.xml, Resources/config/services.xml
This move discovered clients configuration from `HttplugExtension` to `services.xml` and `data-collector.xml`.
=> Use xml to configure discovered clients

DependencyInjection/HttplugExtension.php, Discovery/ConfiguredClientsStrategy.php, Resources/config/services.xml, Tests/Functional/DiscoveredClientsTest.php, Tests/Unit/Discovery/ConfiguredClientsStrategyTest.php
| New feature?    | yes?
When available (Symfony 3.3+), a `ServiceLocator` is used in the `ConfiguredClientStrategy` to lazy load discoverable clients. A fallback injecting the Container is implemented for older Symfony versions.
This is required to solve a chicken/egg problem for #109. This should also improve a few resources usage by only building clients when discovery is called (before discovered clients were built at `kernel.request` or `console.command`).
=> use service locator for configured client strategy

DependencyInjection/HttplugExtension.php, Discovery/ConfiguredClientsStrategy.php, Resources/config/services.xml, Tests/Functional/DiscoveredClientsTest.php, Tests/Unit/Discovery/ConfiguredClientsStrategyTest.php
This reverts commit c5ac6da7516d6390b7cf8ce01b74fddfe007a839. 
PR #185 made discovery so extra lazy so it does not work. See #188.
=> Revert "use service locator for configured client strategy"

CHANGELOG.md, ClientFactory/DummyClient.php, DependencyInjection/HttplugExtension.php
| Deprecations?   | yes
This deprecate the DummyClient interface which was only used for hinting classes in the DI container. I replaced the only usage with PluginClient as it's what the service really is.
=> Deprecate DummyClient

DependencyInjection/HttplugExtension.php, Tests/Functional/ServiceInstantiationTest.php, Tests/Resources/app/config/config_test.yml, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Related tickets | fixes #191 
This fix #191 by no longer use Symfony dependency injection decoration for plugin profiling.
=> Don't use dependency injection decoration for plugin profiling

CHANGELOG.md, Resources/config/data-collector.xml, Tests/Functional/ProfilerTest.php, Tests/Resources/app/AppKernel.php, composer.json
This fix the profiler panel display when used in a symfony/flex application.
I added a test to ensure the panel is loading (the case is with no requests sent).
The bug was caused by the profiler template path which was using the old twig path syntax (no `@` and `::`).
I also found that the profiler is dependent on the `symfony/asset` component.
=> Fix profiler display when using in a symfony/flex project

Collector/ProfileClient.php, DependencyInjection/HttplugExtension.php, Resources/config/data-collector.xml, Resources/config/services.xml, Tests/Functional/DiscoveredClientsTest.php
| Related tickets | partially #109
This remove the need of a `PluginClient` for discovered clients. Only a `ProfileClient` is used.
This will help to avoid double profiling I'm talking about in #109.
This also contains a commit to make StyleCI happy because it now requires a blank line before `break` instructions.
=> Don't use PluginClient for discovered clients

Collector/Collector.php, Resources/views/webprofiler.html.twig, Tests/Unit/Collector/CollectorTest.php
| Related tickets | partially #109
This is part of #109 and solve some edge cases when displaying the profiler panel:
* don't display empty client tabs in profiler. This happen when the discovery is only used by a third party library.
* return only collector root stacks. This improve template readability.
* better count of client messages. When discovery is forced to a configured client, the message count in the client tab is wrong. This introduce a different way to count messages starting by root stacks and going down to nested requests.
=> minor profiler updates

Tests/Resources/app/AppKernel.php
| Bug fix?        | yes, kind of
When you run the tests you build some cache in your system's temp directory. If you say, bump some versions that cache may not be properly cleared. This fix make sure we always start with a clear cache every time we run the tests.
=> Make sure we use different cache directories every time we run the tests

.travis.yml, DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, Tests/Functional/ProfilingTest.php, Tests/Unit/ClientFactory/BuzzFactoryTest.php, Tests/Unit/ClientFactory/CurlFactoryTest.php, Tests/Unit/ClientFactory/Guzzle6FactoryTest.php, Tests/Unit/ClientFactory/ReactFactoryTest.php, Tests/Unit/ClientFactory/SocketFactoryTest.php, Tests/Unit/Collector/CollectorTest.php, Tests/Unit/Collector/FormatterTest.php, Tests/Unit/Collector/ProfileClientFactoryTest.php, Tests/Unit/Collector/ProfileClientTest.php, Tests/Unit/Collector/ProfilePluginTest.php, Tests/Unit/Collector/StackPluginTest.php, Tests/Unit/Discovery/ConfiguredClientsStrategyTest.php, composer.json, phpunit.xml.dist
=> Moved TEST_COMMAND to global section

.travis.yml, CHANGELOG.md, ClientFactory/PluginClientFactory.php, Collector/PluginClientFactory.php, Collector/PluginClientFactoryListener.php, Collector/PluginClientFactorySubscriber.php, DependencyInjection/HttplugExtension.php, Resources/config/data-collector.xml, Resources/config/services.xml, Tests/Functional/ServiceInstantiationTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php, composer.json
| Related tickets | fixes #109 
| Documentation   | TODO
Here we are! This PR is the journey achievement for 0 config profiling of 3rd party libraries.
It relies on https://github.com/php-http/client-common/pull/83 which will be released with 1.6.0.
In a few words, it uses the `Http\Client\Common\PluginClientFactory::setFactory` internal method to replace the PluginClientFactory internals. By doing so, every 3rd party library which use the  `Http\Client\Common\PluginClientFactory` to create it's client will automatically get profiling when used within a Symfony application.
To be more precise, clients created using the bundle …
=> Add PluginClientFactory support

Resources/config/services.xml
| Documentation   | in/a
MessageFactory has 2 parent interfaces (allowing to typehint against only the part you want). This makes these interfaces work for autowiring too (by using the existing message_factory service, as it implements these interfaces due to this inheritance)
Autowiring is great, and the bundle should make it work fine.
=> Add autowiring for RequestFactory and ResponseFactory

Collector/Collector.php, Tests/Unit/Collector/CollectorTest.php
| Related tickets | fixes #215 
This implement the `DataCollectorInterface::reset` method which will be required to get his bundle working with Symfony 4.
=> Add reset method to collector

CHANGELOG.md, DependencyInjection/HttplugExtension.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Documentation   | https://github.com/php-http/documentation/pull/215
Added missing service reference for `CachePlugin`'s `cache_key_generator` configuration option.
Your are able to replace the default CacheKeyGenerator-Strategy.
=> [CachePlugin] added missing service reference for cache_key_generator

.travis.yml, Tests/Unit/Collector/StackPluginTest.php, composer.json
This will avoid us requiring symfony/symfony
=> Updated travis yml to properly test different symfony versions

.travis.yml
=> cache PhpUnitBridge dependencies between builds

composer.json
With `prefer-stable` set to `true`, the `DEPENDECIES=dev` build job
will (almost) never install not yet released dependencies. Without
the `prefer-stable` setting we should also drop the `minimum-stability`
setting (which is now useless as the config value is set in the Travis
job).
=> remove stability settings from composer.json

phpunit.xml.dist
There is no need to log all notices when running tests. Seeing just critical errors is sufficient.
=> turn off unneeded noise in tests

Collector/ProfileClient.php, Tests/Functional/Issue206.php
=> Use flex client wrapper for profiling if needed

composer.json
To make it easier to see which dependencies are actually required
packages are now sorted. That was not a technical requirement.
* added `symfony/config`, this package is needed by the dependency
injection extension
* added `symfony/http-kernel` which provides the base `Bundle` class
* added `php-http/httplug` and `psr/http-message` which provide
interfaces the bundle relies on to be present
* moved `symfony/framework-bundle` to the `require-dev` section, it is
only needed in tests where the `WebTestCase` class is used for
functional tests
* added `guzzlehttp/psr7`, `php-http/promise`, `symfony/stopwatch`, and
`symfony/http-foundation` as dev dependencies
* removed `phpunit/php-token-stream`, `symfony/finder`, and
`symfony/twig-bridge` from `require-dev`
=> update the list of required dependencies

CHANGELOG.md
make changelog more clear to read for users
=> improve changelog

LICENSE
This is not needed. You will automatically have copy right for what ever you create for 50(?) years.
=> Removed "end year" form the license file

CHANGELOG.md, Collector/PluginClientFactoryListener.php, Tests/Unit/Collector/PluginClientFactoryListenerTest.php
| Related tickets | fix #238
The bug is fixed in PHP 7.0.7 but not in the 5.6 branch. I'm adding a test to get confirmation it's breaking. Then fix the bug.
=> Work around same-name import bug in PHP 5.6

DependencyInjection/HttplugExtension.php, Tests/Resources/Fixtures/config/cache_config_with_no_pool.yml, Tests/Resources/Fixtures/config/client_cache_config_with_no_pool.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Related tickets | fixes #244 
These abstract definitions are needed for client plugin definitions, even if plugins weren't configured at root level.
Allows to configure plugin this way
``` yaml
httplug:
clients:
test:
plugins:
- cache:
cache_pool: my_cache_pool
```
instead of forcing unneeded configuration at httplug.plugins.cache level. See linked issue.
=> Don't remove abstract plugins

ClientFactory/MockFactory.php, DependencyInjection/HttplugExtension.php, Resources/config/mock-client.xml, Resources/config/services.xml, Tests/Unit/ClientFactory/MockFactoryTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php, composer.json
| Related tickets | fixes partially #212 
| Documentation   | https://github.com/php-http/documentation/pull/220
Add a mock client factory to ease functional testing.
Configuration:
```yaml
httplug:
clients:
my_awesome_client:
factory: 'httplug.factory.mock' # replace factory
```
Usage:
``` php
$client = static::createClient();
// $client->disableReboot(); You might uncomment this if your client (BrowserKit) make multiple requests as kernel is rebooted on each request.
$response = $this->createMock('Psr\Http\Message\ResponseInterface');
$response->method('getBody')->willReturn(/* Psr\Http\Message\Interface instance containing …
```
=> Add mock client factory for test purpose.

Tests/Resources/Fixtures/config/empty.yml
This will fix our broken master. 
Related to https://github.com/symfony/symfony/pull/25891
=> Empty configuration should not contain any data.

DependencyInjection/HttplugExtension.php
Symfony 3.4+ is making services private by default, so this requires configuring the visibility explicitly.
This allows keeping `$this->get('httplug.client')` working without deprecation.
For now, I haven't applied this change to the different client services, but it might make sense as well.
=> Make main aliases public

Tests/Resources/app/config/config_debug.yml, Tests/Resources/app/config/config_test.yml
This will fix the following deprecation notice: 
```
8x: Relying on the default value ("false") of the "twig.strict_variables" configuration option is deprecated since Symfony 4.1. You should use "%kernel.debug%" explicitly instead, which will be the new default in 5.0.
2x in DiscoveredClientsTest::testDiscoveredClient from Http\HttplugBundle\Tests\Functional
2x in DiscoveredClientsTest::testDiscoveredClientWithProfilingEnabled from Http\HttplugBundle\Tests\Functional
2x in DiscoveredClientsTest::testDisabledDiscovery from Http\HttplugBundle\Tests\Functional
2x in …
```
=> Use twig.strict_variables: '%kernel.debug%'

Tests/Resources/app/AppKernel.php
Symfony 4.1 has deprecated the single colon syntax when defining routes.
=> Register routes sf 4.1 style

Tests/Functional/ProfilerTest.php
| Related tickets | #267 
Xpath did not work. I've got no idea why. It might be the big script tag in `#collector-content` that causes issues. 
I spent a good 30 minutes trying with my limited xpath skill without any success. I finally decided to do a simple strpos. 
Because master build is red on travis.
=> Use strpos instead of Xpath

DependencyInjection/Configuration.php, DependencyInjection/HttplugExtension.php, Tests/Unit/DependencyInjection/ConfigurationTest.php
| Related tickets | fixes #265 
| Documentation | https://github.com/php-http/documentation/pull/238
Add missing support for the `QueryParam` auth plugin.
Because there is no reason to not have it. :-D
=> Add QueryParam auth plugin support

CHANGELOG.md, DependencyInjection/Configuration.php
=> Avoid deprecated notice when using symfony/config > 4.2

Tests/Functional/DiscoveryTest.php, Tests/Unit/Collector/FormatterTest.php, Tests/Unit/DependencyInjection/HttplugExtensionTest.php
Add some assertions in tests that previously had none.
To avoid risky tests that don't really test anything.
=> improve some of the tests

Collector/Formatter.php, Collector/PluginClientFactory.php, Collector/ProfileClient.php, Collector/ProfileClientFactory.php, Tests/Functional/ServiceInstantiationTest.php, Tests/Resources/MyPsr18TestClient.php, Tests/Resources/app/AppKernel.php, Tests/Resources/app/config/config_psr18.yml, composer.json
| Related tickets | fixes #276
=> Make sure we support any psr-18 client

.travis.yml
increase the available memory limit for Composer to successfully execute the SAT solver
build jobs terminate with memory limit being reach errors
=> use more memory for Composer's solving process

CHANGELOG.md, DependencyInjection/HttplugExtension.php, composer.json
| BC breaks?      | yes
| Related tickets | fixes #300
Require Twig to be installed when the profiler is enabled. Move `twig/twig` dependency to suggest and `require-dev`
We don't have Twig installed in our project. HTTPlug requires it to be installed.
=> Only require Twig when profiler is enabled

Collector/Formatter.php, Collector/ProfileClient.php
| Related tickets | fixes #304
=> don't call getResponse() on RequestExceptionInterface

CHANGELOG.md, DependencyInjection/HttplugExtension.php
this only happens for the "default" client: the first configured client or the one called default.
| Related tickets | fixes #261 
Autowire the convenience clients
This is the expected behaviour. We only autowire them if the default client has the decorators to avoid unexpected random autowiring.
=> support autowire convenience clients

CHANGELOG.md, DependencyInjection/Configuration.php, composer.json
| BC breaks?      | not really
| Related tickets | fixes #310 
| Documentation   | https://github.com/php-http/documentation/pull/254
Remove hard dependency on the cache plugin.
When no caching is configured, the bundle does not need that package.
=> cache-plugin is not a hard dependency to use this bundle

CHANGELOG.md, src/DependencyInjection/Configuration.php, tests/Resources/Fixtures/config/invalid_captured_body_length.yml, tests/Resources/Fixtures/config/limitless_captured_body_length.yml, tests/Unit/DependencyInjection/ConfigurationTest.php
| Documentation   | https://github.com/php-http/documentation/pull/259
This PR allow to set the `httpplug.profiling.captured_body_length` to `NULL` to avoid body truncate in the Symfony profiler.
I want to view all the body content of a `Request` or `Response`.
=> Allow to disable body limitation size

src/DependencyInjection/Configuration.php, tests/Unit/DependencyInjection/ConfigurationTest.php
| Related tickets | cleanup after https://github.com/php-http/HttplugBundle/pull/322#pullrequestreview-212272827
Simplify the configuration validation as proposed by @xabbuh
=> simplify configuration validation

src/DependencyInjection/HttplugExtension.php
avoid a deprecation warning and do not fail when a new major version of twig drops the old underscore-namespaced BC layer.
=> also check for new twig environment class for when they remove the non-namespaced layer

CHANGELOG.md
| Related tickets | https://github.com/php-http/HttplugBundle/issues/324
Mentioned https://github.com/php-http/HttplugBundle/pull/327, https://github.com/php-http/HttplugBundle/pull/326 and https://github.com/php-http/HttplugBundle/pull/305 in the changelog. Hope that's all based on https://github.com/php-http/HttplugBundle/compare/1.14.0...c88cc45df62e586a2894304ef83e465c4ae2aadf
=> Improve changelog for 1.15.0 release

src/DependencyInjection/HttplugExtension.php
| Related tickets | no
Fix an undefined variable `$serviceId` when the first client is named default in configuration
Fix an undefined variable `$serviceId` when the first client is named default in configuration
- [ x] Documentation pull request created (if not simply a bugfix)
=> Fix error on undefined variable when a client is named default in config

CHANGELOG.md, src/DependencyInjection/HttplugExtension.php, tests/Resources/Fixtures/config/full.php, tests/Resources/Fixtures/config/full.xml, tests/Resources/Fixtures/config/full.yml, tests/Unit/DependencyInjection/ConfigurationTest.php, tests/Unit/DependencyInjection/HttplugExtensionTest.php
Removes the `enabled` key from the `$config` array passed to the `ContentTypePlugin` constructor options.
The `content_type` plugin configuration can be enabled and thus has an `enabled` option in it's configuration. If this is passed without removing the `enabled` key, the options resolver of the `ContentTypePlugin` constructor options throws an exception:
```
The option "enabled" does not exist. Defined options are: "size_limit", "skip_detection".
```
=> Remove enabled key from content type plugin options

phpunit.xml.dist
This PR
Running
```
$ composer install && composer test
```
on current `master` yields
```
PHPUnit 7.4.5 by Sebastian Bergmann and contributors.
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 8:
- Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.
Line 33:
- Element 'php': This element is not expected.
Test results may not be as expected.
```
=> Fix: Clean up phpunit.xml.dist

README.md
This PR
Since this package requires at least PHP 7.1, I think it's safe to use short array syntax in code examples.
=> Enhancement: Use short array syntax in README.md

CHANGELOG.md, composer.json
| Related tickets | continues #340
Also drops support for Symfony 4.0 and 4.1 which do not receive bugfixes anymore.
see #340
=> drop support for unmaintained Symfony versions

.travis.yml, CHANGELOG.md, composer.json, src/ClientFactory/CurlFactory.php, tests/Unit/ClientFactory/CurlFactoryTest.php, tests/Unit/DependencyInjection/HttplugExtensionTest.php
| BC breaks?      | yes
| Related tickets | fix #338 
This PR contains the compatibility with php-http/curl-client v2.
Installing the bundle with the curl-client will trigger that error now :
```
Argument 1 passed to Http\Client\Curl\Client::__construct() must be an instance of Psr\Http\Message\ResponseFactoryInterface or null, instance of Nyholm\Psr7\Factory\HttplugFactory given, called in /vagrant/vendor/php-http/httplug-bundle/src/ClientFactory/CurlFactory.php on line 5
```
=> Add compatibility with curl-client v2 (now relying on PSR17 factories)

tests/Unit/ClientFactory/MockFactoryTest.php
This PR
When applying the following patch 
```diff
diff --git a/src/ClientFactory/MockFactory.php b/src/ClientFactory/MockFactory.php
index c56d38c..e57d373 100644
--- a/src/ClientFactory/MockFactory.php
+++ b/src/ClientFactory/MockFactory.php
@@ -10,11 +10,6 @@ use Http\Mock\Client;
*/
final class MockFactory implements ClientFactory
{
-    /**
-     * @var HttpClient
-     */
-    private $client;
-
/**
* Set the client instance that this factory should return.
*
@@ -22,7 +17,6 @@ final class MockFactory implements ClientFactory
*/
public function setClient(HttpClient $client)
{ …
```
=> Fix: Use assertSame()

tests/Functional/DiscoveredClientsTest.php, tests/Functional/DiscoveryTest.php, tests/Functional/Issue206.php, tests/Functional/ProfilerTest.php, tests/Functional/ProfilingTest.php, tests/Functional/ServiceInstantiationTest.php, tests/Resources/app/AppKernel.php, tests/Unit/ClientFactory/BuzzFactoryTest.php, tests/Unit/ClientFactory/CurlFactoryTest.php, tests/Unit/ClientFactory/Guzzle6FactoryTest.php, tests/Unit/ClientFactory/MockFactoryTest.php, tests/Unit/ClientFactory/ReactFactoryTest.php, tests/Unit/ClientFactory/SocketFactoryTest.php, tests/Unit/Collector/CollectorTest.php, tests/Unit/Collector/FormatterTest.php, tests/Unit/Collector/PluginClientFactoryListenerTest.php, tests/Unit/Collector/ProfileClientFactoryTest.php, tests/Unit/Collector/ProfileClientTest.php, tests/Unit/Collector/ProfilePluginTest.php, tests/Unit/Collector/StackPluginTest.php, tests/Unit/DependencyInjection/ConfigurationTest.php, tests/Unit/DependencyInjection/HttplugExtensionTest.php, tests/Unit/Discovery/ConfiguredClientsStrategyTest.php
This PR
I ran
```
$ php-cs-fixer fix --allow-risky=yes --diff --verbose --rules=void_return tests
```
We require at least PHP 7.1, so why not?
=> Enhancement: Apply void_return fixer to tests

.php_cs.dist
This PR
Somewhat related to #348.
The minimum required PHP version is PHP 7.1, so we might just as well make use of the features.
=> Enhancement: Configure visibility_required fixer

CHANGELOG.md, src/DependencyInjection/HttplugExtension.php, tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Related tickets | related to #346
| Documentation   | https://github.com/php-http/documentation/pull/268
This PR 
This would allow fetching services by tag and replacing them, for example, with a concrete `Mock\Client`, without having to know the exact service identifier.
=> Enhancement: Tag clients

CHANGELOG.md, src/Collector/Formatter.php, src/Collector/ProfileClient.php, tests/Unit/Collector/ProfileClientTest.php
Fix error 
```
TypeError: Argument 1 passed to Http\HttplugBundle\Collector\ProfileClient::collectExceptionInformations() must be an instance of Exception, instance of TypeError given, called in /home/spolischook/www/mobile-api/vendor/php-http/httplug-bundle/src/Collector/ProfileClient.php on line 144
```
- [] If the PR is not complete but you want to discuss the approach, list what remains to be done here
=> TypeError: Argument 1 passed to ProfileClient::collectExceptionInformations() must be an instance of Exception

CHANGELOG.md, src/Collector/ProfileClient.php, src/Collector/Stack.php, src/Resources/views/stack.html.twig
If a response contains a header `X-Debug-Token-Link`, i.e. a link to a Symfony debug toolbar profiler page, a clickable link is added to easily navigate to it.
This is purely for a more convenient debugging when investigating Responses from a (different) Symfony application.
=> Adds link to debug token.

CHANGELOG.md, composer.json, src/Collector/ProfileClient.php, src/Collector/Stack.php, src/Collector/Twig/HttpMessageMarkupExtension.php, src/Resources/config/data-collector.xml, src/Resources/views/http_message.html.twig, src/Resources/views/stack.html.twig, tests/Functional/ProfilerTest.php, tests/Functional/ServiceInstantiationTest.php
| Deprecations?   | yes
| Related tickets | partially #245
| Documentation   |
Improved profiler design. Check [Before](https://user-images.githubusercontent.com/496233/69001989-3605b500-08e8-11ea-90b2-9a1c7b6d0b3f.png) and [After](https://user-images.githubusercontent.com/496233/69001956-dc9d8600-08e7-11ea-91a0-f44dad85a106.png). Also check linked issue.
- `<t(d|h)>` text trimming. I just want to make this simple first time. This can be added in future, at this time horizontal scrolling works perfect here.
- Syntax highlighting for body. Should be done in separate PR, I want to minimze scope here which will help review and merge this faster.
=> [Profiler] Use tabular design for HTTP request/headers

.travis.yml
| Related tickets | no
| Documentation   | no
PHP 7.4 released, and we need run tests for 7.4 too
=> Add php 7.4 for travis

.travis.yml, CHANGELOG.md
I've confirmed that the change log is up to date. 
I'm happy to release a new version =)
=> Release 1.17

src/Resources/config/data-collector.xml
we still have the trigger deprecation in the php code of the twig extension.
avoid unnecessary deprecation warning, fix #371
=> do not deprecate on twig extension service definition

src/Resources/views/stack.html.twig
| Documentation   |
Replaces usages of the Twig `include` tag with the `include()` function.
Twig best practice is to use the function instead of the tag:
> It is recommended to use the include function instead as it provides the same features with a bit more flexibility [...]
see https://twig.symfony.com/doc/3.x/tags/include.html
=> replace the include tag with the include() function

.travis.yml, src/ClientFactory/SymfonyFactory.php, src/Resources/config/services.xml, tests/Unit/ClientFactory/SymfonyFactoryTest.php
This PR is blocked by #372. It will allow you to configure Symfony clients like: 
```yaml
httplug:
clients:
default:
factory: 'httplug.factory.symfony'
http_methods_client: true
config:
timeout: 4  # Symfony config
plugins:
- 'httplug.plugin.logger'
```
=> Add a Symfony client factory

README.md
=> simplify readme for symfony flex and link to documentation

CHANGELOG.md, src/DependencyInjection/HttplugExtension.php, src/Resources/config/plugins.xml
Make plugin service templates abstract
Avoid warning from Symfony
=> make plugin service templates abstract to avoid warning

.travis.yml
| Related tickets | trying to reproduce #385
Lowest version build should be done with lowest supported PHP version, as we otherwise might accidentally install a newer version of a package because the oldest allowed version does not support a newer PHP version.
=> test lowest version with lowest supported php version, not highest

CHANGELOG.md, src/Discovery/ConfiguredClientsStrategy.php, src/Discovery/ConfiguredClientsStrategyListener.php, src/Resources/config/services.xml, tests/Functional/DiscoveredClientsTest.php
| BC breaks?      | technically speaking yes (but I would assume this class should be considered internal?)
This splits the listener from the `ConfiguredClientsStrategy`.
The listener only executes a static call. This avoids initializing the dependencies (including HttpClient) on each request/command call.
Not sure if any of these checks should be done for this PR?
=> Split listener from ConfiguredClientsStrategy

CHANGELOG.md, src/DependencyInjection/HttplugExtension.php
| New feature?    |yes
| Related tickets |
When you are using Symfony 5.3 and you have multiple clients defined, you can use the `Target`
attribute to select the client that you want.
Improve Developer Experience.
Example:
```php
final class MyService
{
public function __construct(
#[Target('my_client_alias')] 
HttpClient $client
) {}
}
```
It will now automatically inject `httplug.client.my_client_alias`.
For more information:
https://symfony.com/blog/new-in-symfony-5-3-service-autowiring-with-attributes
=> Register client alias to support Symfony 5.3 Target attribute

src/DependencyInjection/HttplugExtension.php
| Deprecations?   |yes
After https://github.com/php-http/HttplugBundle/pull/393 was merged I started using it in my project and soon discovered that `HttpClient` is deprecated and that the `ClientInterface` from Psr should be used instead.
This will deprecate the alias registration for HttpClient when the ClientInterface is found. 
It will also register the alias for the ClientInterface.
=> Use `ClientInterface` instead of `HttpClient` interface when registering aliases

src/DependencyInjection/HttplugExtension.php
| Bug fix?        |yes
| Related tickets | see #394
Turns out that `Alias::setDeprecated` changed a lot between Symfony versions. I couldn't find a way to distinguish between them so decided to just remove the deprecation for now.
=> Do not deprecate alias as it changed a lot in different Symfony versions

CHANGELOG.md, src/Collector/Twig/HttpMessageMarkupExtension.php, src/Resources/config/data-collector.xml, src/Resources/views/http_message.html.twig, tests/Functional/DiscoveredClientsTest.php
| Related tickets | finishes #245
Similarly like `symfony/http-client` and other bundles, this utilizes `symfony/var-dumper` to format request/response body messages.
Json detection was partially taken over from [csa/guzzle-bundle](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Twig/Extension/GuzzleExtension.php#L52)
This results in much improved design of body formatting, replacing plain nl2br that was used till now.
=> [Profiler] Utilize symfony/var-dumper for dumping response body 

CHANGELOG.md, src/Resources/views/webprofiler.html.twig
Count here is similarly important like number of queries that doctrine-bundle shows, so it should be also displayed at all times
Always shows badge counter here instead of only when there are errors
This info is always important, similarly like # of queries in ORM - people should try to keep it low
=> [Profiler] Always show badge with request count

CHANGELOG.md, src/Resources/views/stack.html.twig
When URL from here 
was copied, result of the clipboard was `http:// fe-client.ek.test /shopping_dev.php/category/7077?page_type=cgp&category_ids%5B0%5D=7077&deviceoutput=desktop&browser=firefox&browser_version=92&user_test_group=2`
=> Fix issue with whitespaces in URL when URL in tab was copied

CHANGELOG.md, src/Resources/config/plugins.xml
| BC breaks?      | maybe, but unlikely
It's pretty non-standard that bundles are using default "app" channel. It misleads users into thinking this is a log coming from application directly and breaks most of the channel filters which assume "app" channels are coming from application directly.
=> Changed default logging plugin monolog channel from "app" to "httplug"

CHANGELOG.md, src/Collector/Twig/HttpMessageMarkupExtension.php
| Bug fix?        | no|**yes**
| New feature?    | **no**|yes
| BC breaks?      | **no**|yes
| Deprecations?   | **no**|yes
Fixes this deprecation notice in PHP 8.1:
> Deprecated: Optional parameter $cloner declared before required parameter $dumper is implicitly treated as a required parameter in {project}/vendor/php-http/httplug-bundle/src/Collector/Twig/HttpMessageMarkupExtension.php on line 29
=> Fix PHP 8.1 deprecation notice

.github/workflows/continuous-integration.yml
| Related tickets | #407
Adds PHP 8.1 to CI. Currently installs RC6.
So that we can verify that it works properly on PHP 8.1.
=> Add PHP 8.1 to CI

CHANGELOG.md, src/DependencyInjection/Configuration.php, tests/Resources/Fixtures/config/ttl_null.yml, tests/Unit/DependencyInjection/ConfigurationTest.php
| New feature?    | yes (allow configuring existing feature of cache plugin)
| Related tickets | fixes #410
=> allow to configure default_ttl to null

CHANGELOG.md, src/DependencyInjection/Configuration.php, src/DependencyInjection/HttplugExtension.php
| Related tickets | fixes #415
=> correctly handle null value for respect_response_cache_directives 

CHANGELOG.md, src/DependencyInjection/Configuration.php
Fix
Invalid type for path "httplug.clients.xxx.plugins.xxx.cache.config.cache_lifetime". Expected "int", but got "null".  
cache_lifetime must be an integer or null
``` yaml
cache_lifetime: ~
```
=> cache_lifetime must be an integer or null

CHANGELOG.md, src/DependencyInjection/Configuration.php, src/DependencyInjection/HttplugExtension.php, tests/Unit/DependencyInjection/ConfigurationTest.php, tests/Unit/DependencyInjection/HttplugExtensionTest.php
| Documentation   | https://github.com/php-http/documentation/pull/297
Makes the error plugin configurable in HttplugBundle.
As far as I can tell, enabling the ErrorPlugin via  configuration is currently not easily possible. For applications it can make sense to violate the PSR-18 spec and have this configuration enabled, so adding it to the bundle seems reasonable to me.
``` yaml
httplug:
clients:
my_client:
factory: 'httplug.factory.guzzle7'
config:
connect_timeout: 1
timeout: 10
force_ip_resolve: 'v4'
plugins:
- error: ~
```
=> Make error plugin configurable

.github/workflows/continuous-integration.yml, composer.json, src/ClientFactory/SocketFactory.php
https://github.com/php-http/socket-client/blob/master/src/Client.php#L51
=> chore: remove php-http/socket-client<2.0 support

CHANGELOG.md, src/Collector/Collector.php, src/DependencyInjection/HttplugExtension.php, src/Resources/views/http_message.html.twig, src/Resources/views/stack.html.twig, tests/Functional/ProfilingTest.php, tests/Resources/app/config/config_test.yml
| Bug fix?        | yes, DX fix
| Related tickets | fixes #420
Report when the captured_body_length is configured 0 (the default value). This is better than we currently just saying that there is no captured body.
Improve DX. See #420
=> tell user if body capturing was disabled

CHANGELOG.md, src/Resources/views/stack.html.twig
See 
Looks like in case target doesn't have leading slash, profiler shows strange URL
=> Profiler: Add slash if there is none between host and path
